import type { ReactNode } from "react";
import {
  Folder,
  Layers,
  FileCode,
  BookOpen,
  Shield,
  Bug,
  BrainCircuit,
  HeartPulse,
  Code2,
  Monitor,
  Server,
  Database,
  Lock,
  TestTube,
  Cloud,
  Package,
  
} from "lucide-react";

import type {
  AnalysisData,
  TechnologyData,
  ArchitectureData,
  Health,
  AIReview,
  Bug as BugType,
  SecurityIssue,
} from "../../types/analysis";

type SummaryTabProps = {
  analysis: AnalysisData;
  technology: TechnologyData;
  architecture: ArchitectureData;
  health: Health;
  aiReview: AIReview;
  bugs: BugType[];
  security: SecurityIssue[];
};

export default function SummaryTab({
  analysis,
  technology,
  architecture,
  health,
  aiReview,
  bugs,
  security,
}: SummaryTabProps) {
  return (
    <div className="mx-auto mt-8 max-w-7xl px-8">

      {/* ================= Header ================= */}

      <div className="mb-8">

  <h2 className="text-3xl font-bold text-slate-900">
    Project Summary
  </h2>

  <p className="mt-2 text-slate-500">
    Complete overview of your software project generated by Lensify.
  </p>

</div>

<div className="mb-8">

  
  

</div>


      {/* ================= Executive Summary ================= */}

      <section className="mb-8 rounded-3xl border border-blue-200 bg-gradient-to-r from-blue-50 to-indigo-50 p-8 shadow-sm">

        <div className="flex items-center gap-3 mb-5">
          <BrainCircuit className="h-8 w-8 text-blue-600" />
          <h3 className="text-2xl font-bold text-slate-900">
            Executive Summary
          </h3>
        </div>

        <p className="leading-8 text-slate-700 text-lg">

          Lensify analysed{" "}
          <strong>{analysis.total_files}</strong> source files
          {analysis.total_lines && (
            <>
              {" "}containing{" "}
              <strong>{analysis.total_lines.toLocaleString()}</strong>{" "}
              lines of code
            </>
          )}
          .

          <br /><br />

          The project achieved a health score of{" "}
          <strong>{health.score}% ({health.status})</strong>.

          <br /><br />

          The analysis detected{" "}
          <strong>{bugs.length}</strong>{" "}
          {bugs.length === 1 ? "bug" : "bugs"} and{" "}
          <strong>{security.length}</strong>{" "}
          {security.length === 1
            ? "security issue"
            : "security issues"}.

          <br /><br />

          The application primarily uses{" "}
          <strong>{analysis.language}</strong>
          {analysis.frontend &&
            analysis.frontend !== "Not Detected" && (
              <>
                {" "}with{" "}
                <strong>{analysis.frontend}</strong>
              </>
            )}
          {analysis.backend &&
            analysis.backend !== "Not Detected" && (
              <>
                {" "}and{" "}
                <strong>{analysis.backend}</strong>
              </>
            )}.
          
          <br /><br />

          Overall, the project follows a{" "}
          <strong>{architecture.pattern}</strong>{" "}
          architecture. The AI review rates the project as{" "}
          <strong>{aiReview.rating}</strong>, with recommendations focused on improving security, maintainability, and code quality where applicable.

        </p>

      </section>

      {/* ================= Project Overview ================= */}

      <section className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">

        <h3 className="mb-6 text-2xl font-bold">
          📋 Project Overview
        </h3>

        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">

          <InfoCard
            icon={<Folder className="h-6 w-6 text-blue-600" />}
            title="Project Name"
            value={analysis.project_name}
          />

          <InfoCard
            icon={<Layers className="h-6 w-6 text-purple-600" />}
            title="Project Type"
            value={analysis.project_type}
          />

          <InfoCard
            icon={<FileCode className="h-6 w-6 text-green-600" />}
            title="Architecture"
            value={architecture.architecture}
          />

          <InfoCard
            icon={<BookOpen className="h-6 w-6 text-orange-600" />}
            title="README"
            value={analysis.readme ? "Available" : "Not Found"}
          />

        </div>

      </section>

      {/* ======== Part 2 Starts Here ======== */}
            {/* ================= Project Statistics ================= */}

      <section className="mt-8 rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">

        <h3 className="mb-6 text-2xl font-bold">
          📊 Project Statistics
        </h3>

        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">

          <InfoCard
            icon={<Folder className="h-6 w-6 text-blue-600" />}
            title="Total Files"
            value={String(analysis.total_files)}
          />

          <InfoCard
            icon={<Code2 className="h-6 w-6 text-green-600" />}
            title="Lines of Code"
            value={String(analysis.total_lines ?? 0)}
          />

          <InfoCard
            icon={<Layers className="h-6 w-6 text-purple-600" />}
            title="Technologies"
            value={String(analysis.total_technologies ?? 0)}
          />

          <InfoCard
            icon={<Package className="h-6 w-6 text-orange-600" />}
            title="Dependencies"
            value={String(analysis.total_dependencies ?? 0)}
          />

        </div>

      </section>

      {/* ================= Quality Metrics ================= */}

      <section className="mt-8 rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">

        <h3 className="mb-6 text-2xl font-bold">
          📈 Quality Metrics
        </h3>

        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">

          <InfoCard
            icon={<HeartPulse className="h-6 w-6 text-red-500" />}
            title="Health Score"
            value={`${health.score}%`}
          />

          <InfoCard
            icon={<BrainCircuit className="h-6 w-6 text-indigo-600" />}
            title="AI Rating"
            value={aiReview.rating}
          />

          <InfoCard
            icon={<Shield className="h-6 w-6 text-emerald-600" />}
            title="Security Issues"
            value={String(security.length)}
          />

          <InfoCard
            icon={<Bug className="h-6 w-6 text-orange-600" />}
            title="Detected Bugs"
            value={String(bugs.length)}
          />

        </div>

      </section>

      {/* ================= Technology Stack ================= */}

      <section className="mt-8 rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">

        <h3 className="mb-6 text-2xl font-bold">
          🛠 Technology Stack
        </h3>

        <div className="grid gap-5 md:grid-cols-2">

          <TechnologyCard
            title="Languages"
            icon={<Code2 className="h-5 w-5 text-blue-600" />}
            items={
              analysis.language !== "Unknown"
                ? analysis.language.split(" + ")
                : []
            }
          />

          <TechnologyCard
            title="Frontend"
            icon={<Monitor className="h-5 w-5 text-purple-600" />}
            items={technology.dependencies.frontend}
          />

          <TechnologyCard
            title="Backend"
            icon={<Server className="h-5 w-5 text-green-600" />}
            items={technology.dependencies.backend}
          />

          <TechnologyCard
            title="Database"
            icon={<Database className="h-5 w-5 text-cyan-600" />}
            items={technology.dependencies.database}
          />

          <TechnologyCard
            title="Authentication"
            icon={<Lock className="h-5 w-5 text-red-600" />}
            items={technology.dependencies.authentication}
          />

          <TechnologyCard
            title="Testing"
            icon={<TestTube className="h-5 w-5 text-pink-600" />}
            items={technology.dependencies.testing}
          />

          <TechnologyCard
            title="Deployment"
            icon={<Cloud className="h-5 w-5 text-orange-600" />}
            items={technology.dependencies.deployment}
          />

          <TechnologyCard
            title="Package Manager"
            icon={<Package className="h-5 w-5 text-indigo-600" />}
            items={technology.dependencies.package_manager}
          />

        </div>

      </section>

      {/* ======== Part 3 Starts Here ======== */}
            {/* ================= Project Health ================= */}

      <section className="mt-8 rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">

        <div className="mb-6 flex items-center gap-3">

          <HeartPulse className="h-7 w-7 text-blue-600" />

          <h3 className="text-2xl font-bold">
            ❤️ Project Health
          </h3>

        </div>

        <div className="mb-4 flex items-center justify-between">

          <span className="text-lg font-medium text-slate-700">
            Overall Health Score
          </span>

          <span className="text-3xl font-bold text-blue-600">
            {health.score}%
          </span>

        </div>

        <div className="h-4 overflow-hidden rounded-full bg-slate-200">

          <div
            className="h-full rounded-full bg-blue-600 transition-all duration-700"
            style={{
              width: `${health.score}%`,
            }}
          />

        </div>

        <div className="mt-6 rounded-2xl bg-slate-50 p-5">

          <div className="flex items-center justify-between">

            <span className="text-lg font-medium">
              Current Status
            </span>

            <span
              className={`rounded-full px-4 py-2 text-sm font-semibold ${
                health.status === "Excellent"
                  ? "bg-green-100 text-green-700"
                  : health.status === "Good"
                  ? "bg-blue-100 text-blue-700"
                  : health.status === "Average"
                  ? "bg-yellow-100 text-yellow-700"
                  : "bg-red-100 text-red-700"
              }`}
            >
              {health.status}
            </span>

          </div>

          <p className="mt-4 text-slate-600">

            {health.score >= 90 &&
              "Excellent project quality with very few improvements needed."}

            {health.score >= 75 &&
              health.score < 90 &&
              "Good quality project. Minor improvements are recommended."}

            {health.score >= 50 &&
              health.score < 75 &&
              "Average project quality. Several improvements are recommended."}

            {health.score < 50 &&
              "Project quality is poor. Major improvements are required."}

          </p>

        </div>

      </section>

    </div>
  );
}

/* ===========================================================
   Reusable Components
=========================================================== */

type InfoCardProps = {
  icon: ReactNode;
  title: string;
  value: string;
};

function InfoCard({
  icon,
  title,
  value,
}: InfoCardProps) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg">

      <div className="mb-4">
        {icon}
      </div>

      <p className="text-sm text-slate-500">
        {title}
      </p>

      <h3 className="mt-2 break-words text-lg font-semibold text-slate-900">
        {value}
      </h3>

    </div>
  );
}

/* ======== Part 4 Starts Here ======== */

type TechnologyCardProps = {
  title: string;
  icon: ReactNode;
  items: string[];
};

function TechnologyCard({
  title,
  icon,
  items,
}: TechnologyCardProps) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg">

      <div className="mb-4 flex items-center gap-2">

        {icon}

        <h4 className="text-lg font-semibold text-slate-800">
          {title}
        </h4>

      </div>

      {items.length === 0 ? (

        <p className="text-sm text-slate-500 italic">
          Not Detected
        </p>

      ) : (

        <div className="flex flex-wrap gap-2">

          {items.map((item) => (
            <span
              key={item}
              className="rounded-full bg-blue-100 px-3 py-1 text-sm font-medium text-blue-700"
            >
              {item}
            </span>
          ))}

        </div>

      )}

    </div>
  );
}