import { Bot } from "lucide-react";

export default function AISummary() {
  return (
    <section className="max-w-7xl mx-auto px-8 mt-8">

      <div className="rounded-3xl bg-white border border-slate-200 shadow-sm p-8">

        {/* Header */}

        <div className="flex items-center gap-3">

          <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-50">
            <Bot className="h-6 w-6 text-blue-600" />
          </div>

          <div>
            <h2 className="text-2xl font-bold text-slate-900">
              AI Project Summary
            </h2>

            <p className="text-slate-500">
              Generated by Lensify AI
            </p>
          </div>

        </div>

        {/* Divider */}

        <div className="my-6 h-px bg-slate-200" />

        {/* Summary */}

        <p className="leading-8 text-slate-600">

          This project is built using
          <span className="font-semibold text-slate-900">
            {" "}React, FastAPI and PostgreSQL.
          </span>

          <br /><br />

          The application follows a modular architecture with
          reusable components and REST APIs.

          <br /><br />

          <span className="font-semibold">
            Overall Project Health:
          </span>

          {" "}Good

          <br />

          <span className="font-semibold">
            Security Score:
          </span>

          {" "}85 / 100

          <br />

          <span className="font-semibold">
            Highest Priority Issue:
          </span>

          {" "}Hardcoded API Keys detected.

        </p>

      </div>

    </section>
  );
}